### ISSUE TITLE
1.15 series doesn't work with voila standalone server

### ISSUE THREAD

**Issue by ruomad** [jupyter-server/jupyter_server#737]
The 1.15.4 (and as far as I can tell, previous ones as well) do not work with voila when launched as a standalone app (blank display and the new message about a missing authorizer).
It works allright with the voila extension in jupyterlab though (I guess the workaround to use AllowAllAuthorizer doesn't kick in when not in a jupyterlab context).

**Comment by Zsailer** [comment]
Thanks @ruomad. This is indeed bug introduced by #713. Should be fixed by #738

**Comment by ruomad** [comment]
The problem is still here though with the new 1.15.5 version, this time with an explicit error message 
<pre>
[Voila] Using C:\Users\****\AppData\Local\Temp to store connection files
[Voila] Storing connection files in C:\Users\****\AppData\Local\Temp\voila_1giaval3.
[Voila] Serving static files from C:\Users\****\AppData\Local\pypoetry\Cache\virtualenvs\azlab-TXIRGxn6-py3.10\lib\site-packages\voila\static.
[Voila] Voilà is running at:
http://localhost:8866/
[Voila] Kernel started: 3e386e74-bbc0-471e-bd4c-a83a5820d9cb
WARNING:tornado.general:403 GET /voila/files/favicon.ico (::1): File not whitelisted
WARNING:tornado.access:403 GET /voila/files/favicon.ico (::1) 2.73ms
C:\Users\****\AppData\Local\pypoetry\Cache\virtualenvs\azlab-TXIRGxn6-py3.10\lib\site-packages\jupyter_server\auth\decorator.py:66: FutureWarning: The Tornado web application does not have an 'authorizer' defined in its settings. In future releases of jupyter_server, this will be a required key for all subclasses of `JupyterHandler`. For an example, see the jupyter_server source code for how to add an authorizer to the tornado settings: https://github.com/jupyter-server/jupyter_server/blob/653740cbad7ce0c8a8752ce83e4d3c2c754b13cb/jupyter_server/serverapp.py#L234-L256
  warnings.warn(
ERROR:tornado.application:Uncaught exception GET /api/kernels/3e386e74-bbc0-471e-bd4c-a83a5820d9cb/channels?session_id=a265bf70-bad3-4e09-9f82-9fbb09613493 (::1)
HTTPServerRequest(protocol='http', host='localhost:8866', method='GET', uri='/api/kernels/3e386e74-bbc0-471e-bd4c-a83a5820d9cb/channels?session_id=a265bf70-bad3-4e09-9f82-9fbb09613493', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "C:\Users\****\AppData\Local\pypoetry\Cache\virtualenvs\azlab-TXIRGxn6-py3.10\lib\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "C:\Users\****\AppData\Local\pypoetry\Cache\virtualenvs\azlab-TXIRGxn6-py3.10\lib\site-packages\jupyter_server\services\kernels\handlers.py", line 409, in get
    await super(ZMQChannelsHandler, self).get(kernel_id=kernel_id)
  File "C:\Users\****\AppData\Local\pypoetry\Cache\virtualenvs\azlab-TXIRGxn6-py3.10\lib\site-packages\jupyter_server\base\zmqhandlers.py", line 335, in get
    await res
  File "C:\Users\****\AppData\Local\pypoetry\Cache\virtualenvs\azlab-TXIRGxn6-py3.10\lib\site-packages\jupyter_server\services\kernels\handlers.py", line 376, in pre_get
    super(ZMQChannelsHandler, self).pre_get()
  File "C:\Users\****\AppData\Local\pypoetry\Cache\virtualenvs\azlab-TXIRGxn6-py3.10\lib\site-packages\jupyter_server\base\zmqhandlers.py", line 323, in pre_get
    if not self.authorizer.is_authorized(self, user, "execute", "kernels"):
AttributeError: 'NoneType' object has no attribute 'is_authorized'
</pre>

**Comment by Zsailer** [comment]
Ah, thanks @ruomad. Looks like I mixed one more place where a warning is needed. PR on its way.

**Comment by ruomad** [comment]
@Zsailer : Thanks a lot ! it works for me now
